### ISSUE TITLE
stm32f446re port

### ISSUE THREAD

**Issue by CodeOn-ArK** [leech001/MPU6050#5]
Hey I have ported this code for F446RE, considering the fact it is quite pop and F401 is quite old arch. Will u like to view && merge the code if I send a PR?
P.S. The code is working superfine

**Comment by leech001** [comment]
Sure. Thank you very much it will be very curious to see what you have changed and how.

**Comment by CodeOn-ArK** [comment]
It isn't a very big change though, but I think it will help people
I have sent a PR do have a look

**Comment by leech001** [comment]
Add from #6  to [stm32f446re](https://github.com/leech001/MPU6050/tree/stm32f446re) branch
